services:
  astrolabe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42300:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./www/.output:/usr/src/app/.output
